In [1]:
#Jackson van der Werf
#Program to practice hard-coding dataframes, adding onto them, filtering them, and merging

# import pandas
import pandas as pd

# import data and assign to rows/columns
df = pd.DataFrame(columns=['agency_code', 'location', 'population', 'homocides', 'assaults', 'robberies'])
df.set_index('agency_code', inplace=True)

df.loc['UT01803'] = ['Salt Lake City, UT',	191992,	8, 874,	469]
df.loc['TXSPD00'] = ['San Antonio, TX',	1463586,	94,	5465,	1986]
df.loc['CA03711'] = ['San Diego, CA',	1400467,	37,	3601,	1378]
df.loc['MOSPD00'] = ['St. Louis, MO',	317095,	188,	3521,	1790]
df.loc['NY05101'] = ['Suffolk County, NY',	1341453,	24,	895,	677]

df[:2]

                       location population homocides assaults robberies
agency_code
UT01803      Salt Lake City, UT     191992         8      874       469
TXSPD00         San Antonio, TX    1463586        94     5465      1986

In [2]:
#print location column
print(df['location'])

# Print the entire row representing Salt Lake City's data using the .loc[] property
print(df.loc['UT01803'])

# Print each of the column names/headers one-at-a-time
columns = list(df)
for col in columns:
  print(col)

agency_code
UT01803    Salt Lake City, UT
TXSPD00       San Antonio, TX
CA03711         San Diego, CA
MOSPD00         St. Louis, MO
NY05101    Suffolk County, NY
Name: location, dtype: object
location      Salt Lake City, UT
population                191992
homocides                      8
assaults                     874
robberies                    469
Name: UT01803, dtype: object
location
population
homocides
assaults
robberies

In [3]:
# Add a new record

df.loc['FL02902'] = ['Tampa, FL', 364383, 27, 2730, 733]
df

                       location population homocides assaults robberies
agency_code
UT01803      Salt Lake City, UT     191992         8      874       469
TXSPD00         San Antonio, TX    1463586        94     5465      1986
CA03711           San Diego, CA    1400467        37     3601      1378
MOSPD00           St. Louis, MO     317095       188     3521      1790
NY05101      Suffolk County, NY    1341453        24      895       677
FL02902               Tampa, FL     364383        27     2730       733

In [4]:
# Create a new DataFrame that includes the homocides per capita for each location
df1 = pd.DataFrame(columns=['agency_code', 'homocides_per_capita'])
df1.set_index('agency_code', inplace=True)

df1.loc['UT01803'] = [4]
df1.loc['TXSPD00'] =	[6]
df1.loc['CA03711'] =	[3]
df1.loc['MOSPD00'] =	[59]
df1.loc['NY05101'] =	[2]
df1.loc['FL02902'] = [9]
df1

            homocides_per_capita
agency_code
UT01803                        4
TXSPD00                        6
CA03711                        3
MOSPD00                       59
NY05101                        2
FL02902                        9

In [5]:
# Combine that new DataFrame with the prior existing DataFrame
df_merged = pd.merge(df,df1, on=['agency_code'])

# Print the entire combined DataFrame in Pandas format (i.e. not using print())
df_merged

                       location population  ... robberies homocides_per_capita
agency_code                                 ...
UT01803      Salt Lake City, UT     191992  ...       469                    4
TXSPD00         San Antonio, TX    1463586  ...      1986                    6
CA03711           San Diego, CA    1400467  ...      1378                    3
MOSPD00           St. Louis, MO     317095  ...      1790                   59
NY05101      Suffolk County, NY    1341453  ...       677                    2
FL02902               Tampa, FL     364383  ...       733                    9

[6 rows x 6 columns]

In [6]:
# Sort the DataFrame by homicides per capita from greatest to least on the original DataFrame (not a copy)
df_merged = df_merged.sort_values(by='homocides_per_capita', ascending=False)

# Filter/reduce the DataFrame down to only those with more than 50 total homicides OR (not 'and') over 5000 assaults
df_merged = df_merged[(df_merged.homocides_per_capita > 50) | (df_merged.assaults > 5000)]
df_merged

                    location population  ... robberies homocides_per_capita
agency_code                              ...
MOSPD00        St. Louis, MO     317095  ...      1790                   59
TXSPD00      San Antonio, TX    1463586  ...      1986                    6

[2 rows x 6 columns]